import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Account & Data Deletion — Sacred Trails',
  description: 'How to delete your account and data from the Sacred Trails iOS app.',
  alternates: { canonical: 'https://sacredtrails.evelyn-ai.com/account-deletion' },
}

export default function AccountDeletionPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold text-ink mb-2">Account &amp; Data Deletion</h1>
      <p className="text-xs text-stone-400 mb-10">Last updated: 2026-06-15</p>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-forest mb-3">No account required</h2>
        <p className="text-stone-600 text-sm leading-relaxed">
          Sacred Trails does not require you to create an account. The app works entirely offline and stores all data locally on your device. There is no server-side user account to delete.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-forest mb-3">Deleting app data from your device</h2>
        <p className="text-stone-600 text-sm leading-relaxed mb-3">
          All data generated by Sacred Trails (waypoint notes, progress, downloaded route packs) is stored locally on your iPhone or iPad. To delete all app data:
        </p>
        <ol className="list-decimal list-inside text-stone-600 text-sm leading-relaxed space-y-2">
          <li>Open <strong>Settings</strong> on your device.</li>
          <li>Go to <strong>General</strong> → <strong>iPhone Storage</strong> (or iPad Storage).</li>
          <li>Find and tap <strong>Sacred Trails</strong>.</li>
          <li>Tap <strong>Delete App</strong>. This removes the app and all its local data permanently.</li>
        </ol>
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-semibold text-forest mb-3">In-app purchases</h2>
        <p className="text-stone-600 text-sm leading-relaxed">
          Route pack purchases are processed and managed by Apple through the App Store. Deleting the app does not cancel or refund purchases. To manage subscriptions or request a refund, visit <a href="https://reportaproblem.apple.com" className="text-forest hover:underline" target="_blank" rel="noopener noreferrer">reportaproblem.apple.com</a> or contact Apple Support.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-forest mb-3">Contact</h2>
        <p className="text-stone-600 text-sm leading-relaxed">
          For any data-related questions, contact <a href="mailto:papahades01@gmail.com" className="text-forest hover:underline">papahades01@gmail.com</a>. We aim to respond within 14 days.
        </p>
      </section>
    </div>
  )
}
