import fs from 'fs'
import path from 'path'

const FLUTTER_DATA = path.resolve('/Users/chenglungchiang/.openclaw/workspace/products/buencamino-flutter/assets/data')
const OUT_DIR = path.resolve('/Users/chenglungchiang/.openclaw/workspace/products/sacred-trails-web/lib/data')

function fixJsonStrings(text) {
  const result = []
  let inString = false
  let escapeNext = false
  for (const ch of text) {
    if (escapeNext) { result.push(ch); escapeNext = false }
    else if (ch === '\\' && inString) { result.push(ch); escapeNext = true }
    else if (ch === '"') { inString = !inString; result.push(ch) }
    else if (ch === '\n' && inString) { result.push('\\n') }
    else if (ch === '\r' && inString) { /* skip */ }
    else { result.push(ch) }
  }
  return result.join('')
}

function readJson(filePath) {
  try {
    const raw = fs.readFileSync(filePath, 'utf-8')
    return JSON.parse(fixJsonStrings(raw))
  } catch (e) {
    console.error(`Failed to parse: ${filePath}`, e.message)
    return null
  }
}

function slugify(id) {
  return id.replace(/_/g, '-')
}

function detectSystem(id) {
  if (id.startsWith('kumano')) return 'kumano'
  if (id === 'shikoku_henro') return 'shikoku'
  if (id === 'saigoku_33') return 'saigoku'
  return 'camino'
}

// ── Routes ──────────────────────────────────────────────────────────────────
const routes = []

const sectionDir = path.join(FLUTTER_DATA, 'sections')
for (const dir of fs.readdirSync(sectionDir)) {
  if (dir === 'camino_shared') continue
  const metaPath = path.join(sectionDir, dir, 'metadata.json')
  if (!fs.existsSync(metaPath)) continue
  const d = readJson(metaPath)
  if (!d) continue
  routes.push({
    slug: slugify(d.id || dir),
    id: d.id || dir,
    name: d.name || {},
    description: d.description || {},
    totalDistanceKm: d.totalDistanceKm || d.total_km || 0,
    averageDays: d.averageDays || d.estimated_days || 0,
    difficulty: d.difficulty || 'moderate',
    startPoint: d.startPoint || '',
    endPoint: d.endPoint || '',
    country: d.country || d.countryCode || '',
    certificationType: d.certificationType || d.certification || '',
    system: detectSystem(d.id || dir),
  })
}

const kumanoDir = path.join(FLUTTER_DATA, 'kumano')
for (const file of fs.readdirSync(kumanoDir).filter(f => f.endsWith('_metadata.json'))) {
  const d = readJson(path.join(kumanoDir, file))
  if (!d) continue
  routes.push({
    slug: 'kumano-' + slugify(d.id),
    id: d.id,
    name: d.name || {},
    description: d.description || {},
    totalDistanceKm: d.totalDistanceKm || d.total_km || 0,
    averageDays: d.averageDays || d.estimated_days || 0,
    difficulty: d.difficulty || 'moderate',
    startPoint: d.startPoint || '',
    endPoint: d.endPoint || '',
    country: d.country || d.countryCode || 'Japan',
    certificationType: d.certificationType || d.certification || '',
    system: 'kumano',
  })
}

const routesTs = `// AUTO-GENERATED by scripts/extract-data.mjs — do not edit manually
export interface RouteData {
  slug: string
  id: string
  name: Record<string, string>
  description: Record<string, string>
  totalDistanceKm: number
  averageDays: number
  difficulty: string
  startPoint: string
  endPoint: string
  country: string
  certificationType: string
  system: 'camino' | 'kumano' | 'shikoku' | 'saigoku'
}

export const routes: RouteData[] = ${JSON.stringify(routes, null, 2)}

export function getRouteBySlug(slug: string): RouteData | undefined {
  return routes.find(r => r.slug === slug)
}

export function getRoutesBySystem(system: RouteData['system']): RouteData[] {
  return routes.filter(r => r.system === system)
}
`
fs.writeFileSync(path.join(OUT_DIR, 'routes.ts'), routesTs)
console.log(`routes.ts: ${routes.length} routes`)

// ── Waypoints ────────────────────────────────────────────────────────────────
const allWaypoints = readJson(path.join(FLUTTER_DATA, 'waypoints.json')) || []
const waypointsBySlug = {}

for (const w of allWaypoints) {
  const slug = slugify(w.route || '')
  if (!waypointsBySlug[slug]) waypointsBySlug[slug] = []
  waypointsBySlug[slug].push({
    name: w.name || {},
    lat: w.lat || 0,
    lon: w.lon || 0,
    distanceFromStart: w.distanceFromStart || 0,
    elevation: w.elevation || 0,
    hasStamp: w.hasStamp || false,
    stageNumber: w.stageNumber || 0,
    stampDescription: w.stampDescription || {},
    route: slug,
  })
}

for (const file of fs.readdirSync(kumanoDir).filter(f => f.endsWith('_waypoints.json'))) {
  const arr = readJson(path.join(kumanoDir, file)) || []
  const routeId = file.replace('_waypoints.json', '')
  const slug = 'kumano-' + slugify(routeId)
  waypointsBySlug[slug] = arr.map(w => ({
    name: w.name || {},
    lat: w.lat || 0,
    lon: w.lon || 0,
    distanceFromStart: w.distanceFromStart || 0,
    elevation: w.elevation || 0,
    hasStamp: w.hasStamp || false,
    stageNumber: w.stageNumber || 0,
    stampDescription: w.stampDescription || {},
    route: slug,
  }))
}

const waypointsTs = `// AUTO-GENERATED by scripts/extract-data.mjs — do not edit manually
export interface WaypointData {
  name: Record<string, string>
  lat: number
  lon: number
  distanceFromStart: number
  elevation: number
  hasStamp: boolean
  stageNumber: number
  stampDescription: Record<string, string>
  route: string
}

export const waypointsByRoute: Record<string, WaypointData[]> = ${JSON.stringify(waypointsBySlug, null, 2)}

export function getWaypointsForRoute(slug: string): WaypointData[] {
  return waypointsByRoute[slug] ?? []
}

export function getStampWaypointsForRoute(slug: string, limit = 5): WaypointData[] {
  return (waypointsByRoute[slug] ?? [])
    .filter(w => w.hasStamp && w.stampDescription?.en)
    .sort((a, b) => a.stageNumber - b.stageNumber)
    .slice(0, limit)
}
`
fs.writeFileSync(path.join(OUT_DIR, 'waypoints.ts'), waypointsTs)
console.log(`waypoints.ts: routes with waypoints: ${Object.keys(waypointsBySlug).length}`)

// ── POIs ─────────────────────────────────────────────────────────────────────
const poisBySlug = {}

for (const dir of fs.readdirSync(sectionDir)) {
  if (dir === 'camino_shared') continue
  const poisPath = path.join(sectionDir, dir, 'pois.json')
  if (!fs.existsSync(poisPath)) continue
  const arr = readJson(poisPath) || []
  const slug = slugify(dir)
  poisBySlug[slug] = arr.slice(0, 6).map(p => ({
    name: p.name || {},
    type: p.type || '',
    lat: p.lat || 0,
    lon: p.lon || 0,
    details: p.details || {},
    route: slug,
  }))
}

for (const file of fs.readdirSync(kumanoDir).filter(f => f.endsWith('_pois.json'))) {
  const arr = readJson(path.join(kumanoDir, file)) || []
  const routeId = file.replace('_pois.json', '')
  const slug = 'kumano-' + slugify(routeId)
  poisBySlug[slug] = arr.slice(0, 6).map(p => ({
    name: p.name || {},
    type: p.type || '',
    lat: p.lat || 0,
    lon: p.lon || 0,
    details: p.details || {},
    route: slug,
  }))
}

const poisTs = `// AUTO-GENERATED by scripts/extract-data.mjs — do not edit manually
export interface POIData {
  name: Record<string, string>
  type: string
  lat: number
  lon: number
  details: Record<string, string>
  route: string
}

export const poisByRoute: Record<string, POIData[]> = ${JSON.stringify(poisBySlug, null, 2)}

export function getPOIsForRoute(slug: string, limit = 4): POIData[] {
  return (poisByRoute[slug] ?? []).slice(0, limit)
}
`
fs.writeFileSync(path.join(OUT_DIR, 'pois.ts'), poisTs)
console.log(`pois.ts: routes with POIs: ${Object.keys(poisBySlug).length}`)
console.log('Done.')
